//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

[Serializable]
public class AskObject: Object 
{
	int objectID;
	int userID;
	double x, y, globalRadius; 
	
	public AskObject(double xCoord, double yCoord, int objectID, int userID, double global){
		objectId = objectID;
		userId = userID;
		x = xCoord; 
		y = yCoord; 
		globalRadius = global;
		
	}
	
	/** Get the X coordinate of the center. */
	public double getX(){
		return x; 
	}
	
	/** Get the Y coordinate for the center. */
	public double getY(){
		return y; 
	}
	
	/** Returns the globalRadius. */
	public double getRadius() {
		return globalRadius;
	}
}