//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace AskTest{
[Serializable]
public class AskObject: Object 
{
	string objectstream;
	int userId;
	int targetId;
	double[] position=new double[2]; 
	int objectId;
	
	public AskObject(double Coord, string obj, int userID, int objectID, int targetID){
		objectstream = obj;
		userId = userID;
		position=Coord;
		objectId=objectID;
		targetId=targetID;
	}
	
	/** Get the X coordinate of the center. */
	public double getX(){
		return position[0]; 
	}
	
	/** Get the Y coordinate for the center. */
	public double getY(){
		return position[1]; 
	}


	
	/** Returns the globalRadius. */
	// public double getRadius() {
	// 	return globalRadius;
	// }
}
} 